name:  Karate API Tests CI
 
on:
  push:
    branches: [ main ]
    paths:
      - 'src/test/resources/features/**'
      - 'src/test/java/TestRunner.java'
      - 'pom.xml'
 
  pull_request:
    branches: [ main ]
    paths:
      - 'src/test/resources/features/**'
      - 'src/test/java/TestRunner.java'
      - 'pom.xml'
 
jobs:
  run-karate-tests:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name:  Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name:  Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
 
      - name:  Run Karate API tests
        run: mvn test
 
      - name:  Upload Karate HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports
 
 